import pytest
import time
from fastapi.testclient import TestClient
from main import app

client = TestClient(app)

def test_health_endpoint():
    response = client.get("/api/health")
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "healthy"
    assert "AI Software Dependency Risk Analyzer" in data["service"]

# --- SUPPORTED FILE UPLOAD TESTS ---

def test_upload_supported_package_json():
    content = b'{"name": "npm-demo", "dependencies": {"express": "4.16.0"}}'
    response = client.post("/api/scan", files={"file": ("package.json", content, "application/json")})
    assert response.status_code == 200
    data = response.json()
    assert data["filename"] == "package.json"
    assert data["ecosystem"] == "npm"
    assert "factor_contributions" in data
    assert "risk_label" in data
    assert "risk_interpretation" in data
    assert "ai_briefing" in data

def test_upload_supported_package_lock_json():
    content = b'{"name": "npm-lock-demo", "packages": {"": {"dependencies": {"qs": "6.5.1"}}}}'
    response = client.post("/api/scan", files={"file": ("package-lock.json", content, "application/json")})
    assert response.status_code == 200
    data = response.json()
    assert data["filename"] == "package-lock.json"
    assert data["ecosystem"] == "npm"

def test_upload_supported_requirements_txt():
    content = b"flask==0.12.2\nrequests==2.20.0"
    response = client.post("/api/scan", files={"file": ("requirements.txt", content, "text/plain")})
    assert response.status_code == 200
    data = response.json()
    assert data["filename"] == "requirements.txt"
    assert data["ecosystem"] == "PyPI"

def test_upload_supported_requirements_lock_txt():
    content = b"django==2.2.0\nurllib3==1.24.1"
    response = client.post("/api/scan", files={"file": ("requirements-lock.txt", content, "text/plain")})
    assert response.status_code == 200
    data = response.json()
    assert data["filename"] == "requirements-lock.txt"
    assert data["ecosystem"] == "PyPI"

def test_upload_supported_pom_xml():
    content = b"""<project xmlns="http://maven.apache.org/POM/4.0.0">
      <modelVersion>4.0.0</modelVersion>
      <groupId>com.example</groupId>
      <artifactId>demo</artifactId>
      <version>1.0.0</version>
      <dependencies>
        <dependency>
          <groupId>org.apache.logging.log4j</groupId>
          <artifactId>log4j-core</artifactId>
          <version>2.14.1</version>
        </dependency>
      </dependencies>
    </project>"""
    response = client.post("/api/scan", files={"file": ("pom.xml", content, "application/xml")})
    assert response.status_code == 200
    data = response.json()
    assert data["filename"] == "pom.xml"
    assert data["ecosystem"] == "Maven"

def test_upload_supported_yarn_lock():
    content = b"""# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT DIRECTLY.
# yarn lockfile v1
lodash@^4.17.15:
  version "4.17.15"
"""
    response = client.post("/api/scan", files={"file": ("yarn.lock", content, "text/plain")})
    assert response.status_code == 200
    data = response.json()
    assert data["filename"] == "yarn.lock"
    assert data["ecosystem"] == "npm"

# --- REJECT UNSUPPORTED FILE TYPE TESTS ---

def test_reject_unsupported_file_extension():
    content = b"console.log('hello world');"
    response = client.post("/api/scan", files={"file": ("script.js", content, "application/javascript")})
    assert response.status_code == 400
    data = response.json()
    assert "Unsupported file type" in data["detail"]

def test_reject_unsupported_python_file():
    content = b"import os\nprint('hello')"
    response = client.post("/api/scan", files={"file": ("app.py", content, "text/x-python")})
    assert response.status_code == 400
    data = response.json()
    assert "Unsupported file type" in data["detail"]

def test_reject_unsupported_binary_file():
    content = b"\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00"
    response = client.post("/api/scan", files={"file": ("binary.exe", content, "application/octet-stream")})
    assert response.status_code == 400

# --- SCAN FUNCTIONALITY TESTS ---

def test_scan_raw_text():
    payload = {
        "filename": "package.json",
        "content": '{"name": "test", "dependencies": {"lodash": "4.17.15"}}'
    }
    response = client.post("/api/scan/text", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert data["total_deps"] >= 1
    assert data["vulnerable_deps"] >= 1

def test_repeated_scan_sqlite_caching():
    payload = {
        "filename": "package.json",
        "content": '{"name": "cached-demo", "dependencies": {"express": "4.16.0"}}'
    }
    t0 = time.time()
    res1 = client.post("/api/scan/text", json=payload)
    t1 = time.time()
    assert res1.status_code == 200

    res2 = client.post("/api/scan/text", json=payload)
    t2 = time.time()
    assert res2.status_code == 200
    assert (t2 - t1) <= (t1 - t0) + 0.05

def test_past_scans_list_get_and_delete():
    payload = {
        "filename": "requirements.txt",
        "content": "flask==0.12.2"
    }
    scan_res = client.post("/api/scan/text", json=payload)
    assert scan_res.status_code == 200
    scan_id = scan_res.json()["id"]

    list_res = client.get("/api/scans")
    assert list_res.status_code == 200
    scans = list_res.json()
    assert any(s["id"] == scan_id for s in scans)

    get_res = client.get(f"/api/scans/{scan_id}")
    assert get_res.status_code == 200
    assert get_res.json()["id"] == scan_id

    del_res = client.delete(f"/api/scans/{scan_id}")
    assert del_res.status_code == 200

    get_res_after = client.get(f"/api/scans/{scan_id}")
    assert get_res_after.status_code == 404

def test_scan_deletion_cascade_ai_insights():
    from database import get_db_connection
    payload = {
        "filename": "package.json",
        "content": '{"name": "vulnerable-app", "dependencies": {"express": "4.16.0"}}'
    }
    scan_res = client.post("/api/scan/text", json=payload)
    assert scan_res.status_code == 200
    scan_id = scan_res.json()["id"]

    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT COUNT(*) as cnt FROM findings WHERE scan_id = ?", (scan_id,))
    finding_cnt = cursor.fetchone()["cnt"]
    cursor.execute("SELECT COUNT(*) as cnt FROM ai_insights WHERE finding_id IN (SELECT id FROM findings WHERE scan_id = ?)", (scan_id,))
    ai_cnt = cursor.fetchone()["cnt"]
    conn.close()

    assert finding_cnt > 0
    assert ai_cnt > 0

    del_res = client.delete(f"/api/scans/{scan_id}")
    assert del_res.status_code == 200

    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT COUNT(*) as cnt FROM scans WHERE id = ?", (scan_id,))
    assert cursor.fetchone()["cnt"] == 0
    cursor.execute("SELECT COUNT(*) as cnt FROM dependencies WHERE scan_id = ?", (scan_id,))
    assert cursor.fetchone()["cnt"] == 0
    cursor.execute("SELECT COUNT(*) as cnt FROM dependency_edges WHERE scan_id = ?", (scan_id,))
    assert cursor.fetchone()["cnt"] == 0
    cursor.execute("SELECT COUNT(*) as cnt FROM findings WHERE scan_id = ?", (scan_id,))
    assert cursor.fetchone()["cnt"] == 0
    cursor.execute("SELECT COUNT(*) as cnt FROM ai_insights WHERE finding_id IN (SELECT id FROM findings WHERE scan_id = ?)", (scan_id,))
    assert cursor.fetchone()["cnt"] == 0
    cursor.execute("SELECT COUNT(*) as cnt FROM reports WHERE scan_id = ?", (scan_id,))
    assert cursor.fetchone()["cnt"] == 0
    conn.close()

def test_delete_nonexistent_scan():
    response = client.delete("/api/scans/non-existent-uuid-9999")
    assert response.status_code == 404

# --- SECTION 14 ENDPOINT TESTS ---

def test_section_14_project_endpoints():
    # 1. Create project
    create_res = client.post("/api/projects", json={
        "name": "E-Commerce App",
        "ecosystem": "npm",
        "repository_url": "https://github.com/myorg/ecommerce"
    })
    assert create_res.status_code == 200
    proj = create_res.json()
    proj_id = proj["id"]
    assert proj["name"] == "E-Commerce App"

    # 2. List projects
    list_res = client.get("/api/projects")
    assert list_res.status_code == 200
    assert any(p["id"] == proj_id for p in list_res.json())

    # 3. Scan project
    scan_res = client.post(f"/api/projects/{proj_id}/scan", data={
        "filename": "package.json",
        "content": '{"name": "ecommerce", "dependencies": {"axios": "0.18.0"}}'
    })
    assert scan_res.status_code == 200
    scan_id = scan_res.json()["id"]

    # 4. Project scan history
    history_res = client.get(f"/api/projects/{proj_id}/scans")
    assert history_res.status_code == 200
    assert any(s["id"] == scan_id for s in history_res.json())

    # 5. Get Scan Dependencies
    deps_res = client.get(f"/api/scans/{scan_id}/dependencies")
    assert deps_res.status_code == 200
    assert "dependencies" in deps_res.json()

    # 6. Get Scan Findings
    findings_res = client.get(f"/api/scans/{scan_id}/findings")
    assert findings_res.status_code == 200
    assert "findings" in findings_res.json()

    # 7. Get Scan Graph
    graph_res = client.get(f"/api/scans/{scan_id}/graph")
    assert graph_res.status_code == 200
    assert "nodes" in graph_res.json()
    assert "edges" in graph_res.json()

    # 8. Get Scan Report
    report_res = client.get(f"/api/scans/{scan_id}/report")
    assert report_res.status_code == 200
